services:
  llm:
    build: .
    container_name: llm
    ports:
      - "9443:8443"
    environment:
      - TZ=America/Sao_Paulo
      - LLM_MODEL=liquid/lfm2-350m
    volumes:
      - llm_data:/root/.lmstudio
      - ./entrypoint.sh:/usr/entrypoint.sh
    networks:
      - ubva-net

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=America/Sao_Paulo
      - REDIS_PASSWORD=REDACTED
    ports:
      - "6379:6379"
    networks:
      - ubva-net
    command: ["redis-server", "--requirepass", "REDACTED"]

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Sao_Paulo
      - N8N_WEBHOOK_URL=http://localhost:5678
      - N8N_ENCRYPTION_KEY=3tdWwJcpvwjpKcH4qgz7wb7FPhM3m9Vn
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - REDIS_PASSWORD=REDACTED
    volumes:
      - n8n_data:/home/node
    networks:
      - ubva-net


volumes:
  llm_data:
  n8n_data:
  redis_data:

networks:
  ubva-net:
    driver: bridge